require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7.1
  DisplayCopNames: true
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "bin/**/*"
Rails:
  Exclude:
    - "spec/**/*"
# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 100

RSpec/ExampleLength:
  Max: 100
RSpec/NestedGroups:
  Max: 6
RSpec/AnyInstance:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Max: 500
# The guiding principle of classes is SRP, SRP can't be accurately measured by
# LoC
Metrics/ClassLength:
  Max: 1500
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 9
Metrics/AbcSize:
  Max: 56
Metrics/ParameterLists:
  Max: 7
Style/AsciiComments:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
RSpec/MultipleExpectations:
  Enabled: false
# new cops, disable if needed
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
# explicitly disabled unique indexes
Rails/UniqueValidationWithoutIndex:
  Enabled: false
